server:
  port: 8082

spring:
  application:
    name: SpringBoot

  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_gym?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
#    drive-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        format_sql: true
